### ISSUE TITLE
why no scrollbar?

### ISSUE THREAD

**Issue by incantatem1** [WinnerWind/gummy-revived#1]
at least i don't see any.

**Comment by danieltomasz** [comment]
@incantatem1 I have a scrollbar (when I move a mouse it became visible)

**Comment by incantatem1** [comment]
for me that's not the case, is it maybe not working in older app versions?

**Comment by danieltomasz** [comment]
Could try to install the theme in the sandbox plugin? Maybe other plugin or css interferes with you vault

**Comment by incantatem1** [comment]
1. i don't know how
2. no idea which could cause this? i don't really have fancy plugins that mess with the vault in such a way, i think
3. 1.5.12

**Comment by incantatem1** [comment]
ok, tried in restricted mode with no plugins at all, still no scrollbar

**Comment by danieltomasz** [comment]
hi @incantatem1  is there a reason you cannot update to 1.6.5?

**Comment by incantatem1** [comment]
i'm scared of breaking certain plugins and older themes by doing that and i can't find info on which ones would even be affected.

**Comment by danieltomasz** [comment]
can you make a  total copy of your vault (the folder you store the files?) I case if the update will break the one  one you need you can reinstall older version and point Obsidian to the copied folder

I didn have any problem with update and I am using 80+ plugins

**Comment by incantatem1** [comment]
> can you make a total copy of your vault (the folder you store the files?) .In case if the update will break the one one you need you can reinstall older version and point Obsidian to the copied folder (import to include hidden files and folders, not only your notes))
> 
> I didn have any problem with update and I am using 80+ plugins

if you could tell me if the new version breaks any of the existing themes to the point of making them unusable, the theme picker plugin (the most important one for me...), avatar plugin, callout manager, editing toolbar and gallery, that would help a bit.

i still have the installer for the old version. i also make backups of my vault all the time but i make them in bits only for subfolders i recently updated, and having to reinstall them all one by one would be tedious

**Comment by WinnerWind** [comment]
Hi there! I'm sorry I couldn't get back sooner! Weirdly I didn't receive an email about this, I'll look into that.
I'm really glad to have the first issue on my theme, you don't know how much it means to me.

As for the lack of scroll bars, you're right, its missing for me as well.
![image](https://github.com/user-attachments/assets/ab40fc0c-7727-4052-ab7e-ea518e3d9a61)
![image](https://github.com/user-attachments/assets/39e79e56-04ee-46e2-b553-6781e4083367)

This is a remnant of the original Gummy theme, which also had missing scroll bars, however I will add it back as a style setting for accessibility reasons. I will need some time.

**Comment by WinnerWind** [comment]
This issue has been fixed. Please update your theme.
The problem was that in the older piece of code, the CSS for scrollbars were defined before the colour it was using was defined, leading it to be invalid. This weirdly only affected the dark theme, which is probably why Daniel may have been able to see the scroll mode. Such restricted mode hacks will NOT work as CSS is loaded the same regardless.
